name: UltraCore
main: com.slamtheham.ultracore.Main
description: UltraCore a complete remake of the popular skript plugin UltimateEssentialsPro
version: 1.0-SNAPSHOT
authors: [SlamTheHam, Draww]

permissions:
    ultracore.admin:
        description: Gives permission to all admin commands
        default: op
    ultracore.help:
        description: Gives permission to help commands
        default: op            
