name: UltraCore
main: com.slamtheham.ultracore.Main
description: UltraCore a complete remake of the popular skript plugin UltimateEssentialsPro
version: v1
author: Developed by SlamTheHam

commands:
    core:
        usage: /<command> <arg0>
        description: Main plugin command
    teleport:
        usage: /<command> <arg0> <arg1>
        description: Teleportation command
    tp:
        usage: /<command> <arg0> <arg1>
        description: Teleportation command
    tpo:
        usage: /<command> <arg0> <arg1>
        description: Teleportation command  
    tppos:
        usage: /<command> <arg0> <arg1> <arg2>
        description: Teleportation command  
    tphere:
        usage: /<command> <arg0>
        description: Teleportation command
    tpa:
        usage: /<command> <arg0>
        description: Teleportation command  
    tpaccept:
        usage: /<command>
        description: Teleportation command  
    tpdeny:
        usage: /<command>
        description: Teleportation command 
    setspawn:
        usage: /<command>
        description: Teleportation command 
    spawn:
        usage: /<command>
        description: Teleportation command                                                  
permissions:
    core.admin:
        description: Gives permission to all admin commands
        default: op
    core.help:
        description: Gives permission to help commands
        default: op  
    core.tp:
        description: Gives permmsion to all teleport commands
        default: op              